export const INDIAN_LANGUAGES = [
  { id: 'hindi', label: 'Hindi', color: 'bg-orange-500' },
  { id: 'marathi', label: 'Marathi', color: 'bg-red-500' },
  { id: 'punjabi', label: 'Punjabi', color: 'bg-green-500' },
  { id: 'bhojpuri', label: 'Bhojpuri', color: 'bg-purple-500' },
  { id: 'bengali', label: 'Bengali', color: 'bg-yellow-600' },
  { id: 'telugu', label: 'Telugu', color: 'bg-blue-500' },
  { id: 'tamil', label: 'Tamil', color: 'bg-indigo-600' },
  { id: 'gujarati', label: 'Gujarati', color: 'bg-pink-500' },
  { id: 'urdu', label: 'Urdu', color: 'bg-emerald-600' },
  { id: 'kannada', label: 'Kannada', color: 'bg-red-600' },
  { id: 'malayalam', label: 'Malayalam', color: 'bg-teal-600' },
  { id: 'odia', label: 'Odia', color: 'bg-cyan-600' },
  { id: 'assamese', label: 'Assamese', color: 'bg-lime-600' },
  { id: 'rajasthani', label: 'Rajasthani', color: 'bg-yellow-500' },
  { id: 'haryanvi', label: 'Haryanvi', color: 'bg-green-600' },
  { id: 'maithili', label: 'Maithili', color: 'bg-violet-500' },
  { id: 'santali', label: 'Santali', color: 'bg-fuchsia-600' },
  { id: 'kashmiri', label: 'Kashmiri', color: 'bg-rose-500' },
  { id: 'nepali', label: 'Nepali', color: 'bg-sky-500' },
  { id: 'konkani', label: 'Konkani', color: 'bg-amber-500' },
  { id: 'sindhi', label: 'Sindhi', color: 'bg-orange-600' },
  { id: 'dogri', label: 'Dogri', color: 'bg-emerald-500' },
  { id: 'manipuri', label: 'Manipuri', color: 'bg-purple-600' },
  { id: 'bodo', label: 'Bodo', color: 'bg-yellow-700' },
  { id: 'jharkhandhi', label: 'Jharkhandhi', color: 'bg-pink-500' },
  { id: 'nagpuri', label: 'Nagpuri', color: 'bg-indigo-500' },
  { id: 'khortha', label: 'Khortha', color: 'bg-teal-500' },
];

export const REMIX_MODES = [
  { id: 'dj', label: 'DJ Remix', description: 'Bass boost, mid scoop, and echo' },
  { id: 'slowed', label: 'Slowed + Reverb', description: 'Slow playback with atmospheric reverb' },
  { id: 'mashup', label: 'Mashup', description: 'Seamlessly blend tracks together' },
  { id: '3d', label: '3D Audio', description: 'Immersive spatial audio experience' },
  { id: '8d', label: '8D Audio', description: 'Circular movement around your head' },
  { id: '16d', label: '16D Audio', description: 'Hyper-immersive fast rotation' },
  { id: '3d-dj', label: '3D + DJ', description: 'Spatial audio with DJ effects' },
  { id: '3d-slowed', label: '3D + Slowed', description: 'Spatial audio with slowed vibe' },
  { id: '8d-dj', label: '8D + DJ', description: 'Rotating audio with DJ effects' },
  { id: '8d-slowed', label: '8D + Slowed', description: 'Rotating audio with slowed vibe' },
  { id: '16d-dj', label: '16D + DJ', description: 'Fast rotation with DJ effects' },
  { id: '16d-slowed', label: '16D + Slowed', description: 'Fast rotation with slowed vibe' },
];
